build_and_publish_x:
  stage: build
  image: docker:24

  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

  script:
    - docker buildx create --use || true
    - docker buildx inspect --bootstrap

    - docker buildx build \
        --platform linux/amd64,linux/arm64 \
        --build-arg DATABASE_URL="$DATABASE_URL" \
        -f Dockerfile.prod \
        -t $CI_REGISTRY_IMAGE:latest \
        -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA \
        --push .