
services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: comcamp37-service
    restart: unless-stopped
    env_file: .env
    ports:
      - 8980:3030
    networks:
      - internal

networks:
  internal: