
services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: comcamp37-service
    restart: unless-stopped
    env_file: .env
    ports:
      - ${DOCKER_APP_EXPOSE_PORT}:${APP_PORT}
    networks:
      - internal

networks:
  internal: