
services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"

      - "--log.level=DEBUG"
      - "--accesslog=true"

      - "--api.dashboard=true"
      - "--api.insecure=true"

      - "--ping=true"
      - "--ping.entrypoint=health"
      - "--entrypoints.health.address=:8082"
    ports:
      - "8980:80"
      - "8080:8080"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal

  client:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
    env_file: .env
    labels:
      # Treafik Base Config
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`100.108.173.73`) || Host(`100.88.117.62`) || Host(`api.localhost`) || Host(`localhost:3030`) || Host(`dev-api2.comcamp.io`) || Host(`dev-api2.comcamp.io:4842`) || Host(`api.comcamp.io`) || Host(`dev-api.comcamp.io`) || Host(`localhost`) || Host(`dev-cc37.aboutnon.in.th`)"
      - "traefik.http.routers.client.entrypoints=web"
      - "traefik.http.services.client.loadbalancer.server.port=3030"

      # Treafik Health Check Config
      - "traefik.http.services.client.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.client.loadbalancer.healthcheck.interval=5s"

      # # Treafik Rate Limit Config
      # - "traefik.http.middlewares.api-ratelimit.ratelimit.average=1200"
      # - "traefik.http.middlewares.api-ratelimit.ratelimit.burst=2500"
      # - "traefik.http.routers.client.middlewares=api-ratelimit"
    networks:
      - internal

networks:
  internal:
    driver: bridge
