# ---------- BUILD STAGE ----------
FROM node:22-bullseye AS builder

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .


ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
RUN npx prisma generate

RUN pnpm run build

# ---------- RUNTIME STAGE ----------
FROM node:22-slim AS runner

WORKDIR /app

ENV NODE_ENV=prod

RUN npm install -g pnpm

# Copy only needed files from builder
COPY --from=builder /app/package.json ./
COPY --from=builder /app/pnpm-lock.yaml ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

# Use non-root user
USER node

EXPOSE 3030

CMD ["pnpm", "run", "start:prod"]