services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: comcamp-service
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev
    ports:
      - 8000:3030
    networks:
      - internal
