name: ComCamp Backend CI for GHCR

on: 
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        run: |
          docker login --username imjustnon --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -f Dockerfile.prod --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} . --tag ghcr.io/imjustnon/comcamp37-server:latest
          docker push ghcr.io/imjustnon/comcamp37-server:latest